version: "3"
services:
  reverseproxy:
    build:
      context: .

    image: mr3zioo/udacity-c3-reverse-proxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user

    image: mr3zioo/udacity-c3-restapi-user  
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  

    image: mr3zioo/udacity-c3-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  

    image: mr3zioo/udacity-c3-frontend
